In [1]:
# working with pytorch
import torch
print(torch.__version__)

1.3.1


In [2]:
tensor_array = torch.Tensor([[1,2],[3,4]])
tensor_array

tensor([[1., 2.],
        [3., 4.]])

In [3]:
tensor_uninitialized = torch.Tensor(3,3)
torch.numel(tensor_uninitialized)

9

In [4]:
tensor_uninitialized

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
tensor_initialized = torch.rand(2,3)
tensor_initialized

tensor([[0.3959, 0.5094, 0.6365],
        [0.8297, 0.9127, 0.5483]])

In [9]:
tensor_int = torch.randn(5,3).type(torch.IntTensor)
tensor_int

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0, -1,  0],
        [ 0, -1,  0],
        [ 0,  0,  0]], dtype=torch.int32)

In [10]:
tensor_long = torch.LongTensor([1.0,2.0,3.0])
tensor_long

tensor([1, 2, 3])

In [11]:
tensor_Byte = torch.ByteTensor([0,261,1,-5])
tensor_Byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [12]:
torch_ones = torch.ones(10)
torch_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
initial_tensor = torch.rand(2,3)
initial_tensor[0,2]

tensor(0.3347)

In [14]:
initial_tensor[:,1:]

tensor([[0.4764, 0.3347],
        [0.3514, 0.6310]])

In [15]:
initial_tensor.size()

torch.Size([2, 3])

In [16]:
initial_tensor.shape

torch.Size([2, 3])

In [18]:
resized_tensor = initial_tensor.view(6)
resized_tensor.shape

torch.Size([6])

In [19]:
resized_matrix = initial_tensor.view(-1,2)
resized_matrix.shape

torch.Size([3, 2])

In [20]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor)
sorted_tensor

tensor([[0.0162, 0.3347, 0.4764],
        [0.3514, 0.5789, 0.6310]])

In [21]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor,dim=0)
sorted_tensor

tensor([[0.0162, 0.3514, 0.3347],
        [0.5789, 0.4764, 0.6310]])

In [28]:
# computation graph
from torch.autograd import Variable

In [29]:
x = Variable(torch.randn(1,10))

In [35]:
h = Variable(torch.randn(1,20))

In [36]:
w_h = Variable(torch.randn(20,20))

In [37]:
w_x = Variable(torch.randn(20,10))

In [38]:
h_prod = torch.mm(w_h,h.t())

In [39]:
x_prod = torch.mm(w_x,x.t())

In [40]:
next_h = (h_prod + x_prod).tanh()

In [41]:
loss = next_h.sum()

In [43]:
# loss.backward()