In [2]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 0.0],
            [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    0. ]
 [  1.8 135.   99.    0.9]]


In [3]:
# sum all the coulms
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  68.9]


In [4]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 98.69375907]
 [ 2.03389831 43.51464435 33.46203346  0.        ]
 [ 3.05084746 56.48535565 63.70656371  1.30624093]]


In [5]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print (c)

[[-0.30985853  1.33188373 -0.15383178]
 [-0.01042057 -0.15189435  1.54453192]]


In [8]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [9]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c.shape)

(3, 3)


In [3]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(B.shape)

(4, 1)
